# Pandas

In [1]:
import pandas as pd

In [2]:
from pydataset import data

In [3]:
AQ = data('airquality')

In [4]:
AQ

     Ozone  Solar.R  Wind  Temp  Month  Day
1     41.0    190.0   7.4    67      5    1
2     36.0    118.0   8.0    72      5    2
3     12.0    149.0  12.6    74      5    3
4     18.0    313.0  11.5    62      5    4
5      NaN      NaN  14.3    56      5    5
6     28.0      NaN  14.9    66      5    6
7     23.0    299.0   8.6    65      5    7
8     19.0     99.0  13.8    59      5    8
9      8.0     19.0  20.1    61      5    9
10     NaN    194.0   8.6    69      5   10
11     7.0      NaN   6.9    74      5   11
12    16.0    256.0   9.7    69      5   12
13    11.0    290.0   9.2    66      5   13
14    14.0    274.0  10.9    68      5   14
15    18.0     65.0  13.2    58      5   15
16    14.0    334.0  11.5    64      5   16
17    34.0    307.0  12.0    66      5   17
18     6.0     78.0  18.4    57      5   18
19    30.0    322.0  11.5    68      5   19
20    11.0     44.0   9.7    62      5   20
21     1.0      8.0   9.7    59      5   21
22    11.0    320.0  16.6    73      5   22
23     4.0     25.0   9.7    61      5   23
24    32.0     92.0  12.0    61      5   24
25     NaN     66.0  16.6    57      5   25
26     NaN    266.0  14.9    58      5   26
27     NaN      NaN   8.0    57      5   27
28    23.0     13.0  12.0    67      5   28
29    45.0    252.0  14.9    81      5   29
30   115.0    223.0   5.7    79      5   30
31    37.0    279.0   7.4    76      5   31
32     NaN    286.0   8.6    78      6    1
33     NaN    287.0   9.7    74      6    2
34     NaN    242.0  16.1    67      6    3
35     NaN    186.0   9.2    84      6    4
36     NaN    220.0   8.6    85      6    5
37     NaN    264.0  14.3    79      6    6
38    29.0    127.0   9.7    82      6    7
39     NaN    273.0   6.9    87      6    8
40    71.0    291.0  13.8    90      6    9
41    39.0    323.0  11.5    87      6   10
42     NaN    259.0  10.9    93      6   11
43     NaN    250.0   9.2    92      6   12
44    23.0    148.0   8.0    82      6   13
45     NaN    332.0  13.8    80      6   14
46     NaN    322.0  11.5    79      6   15
47    21.0    191.0  14.9    77      6   16
48    37.0    284.0  20.7    72      6   17
49    20.0     37.0   9.2    65      6   18
50    12.0    120.0  11.5    73      6   19
51    13.0    137.0  10.3    76      6   20
52     NaN    150.0   6.3    77      6   21
53     NaN     59.0   1.7    76      6   22
54     NaN     91.0   4.6    76      6   23
55     NaN    250.0   6.3    76      6   24
56     NaN    135.0   8.0    75      6   25
57     NaN    127.0   8.0    78      6   26
58     NaN     47.0  10.3    73      6   27
59     NaN     98.0  11.5    80      6   28
60     NaN     31.0  14.9    77      6   29
61     NaN    138.0   8.0    83      6   30
62   135.0    269.0   4.1    84      7    1
63    49.0    248.0   9.2    85      7    2
64    32.0    236.0   9.2    81      7    3
65     NaN    101.0  10.9    84      7    4
66    64.0    175.0   4.6    83      7    5
67    40.0    314.0  10.9    83      7    6
68    77.0    276.0   5.1    88      7    7
69    97.0    267.0   6.3    92      7    8
70    97.0    272.0   5.7    92      7    9
71    85.0    175.0   7.4    89      7   10
72     NaN    139.0   8.6    82      7   11
73    10.0    264.0  14.3    73      7   12
74    27.0    175.0  14.9    81      7   13
75     NaN    291.0  14.9    91      7   14
76     7.0     48.0  14.3    80      7   15
77    48.0    260.0   6.9    81      7   16
78    35.0    274.0  10.3    82      7   17
79    61.0    285.0   6.3    84      7   18
80    79.0    187.0   5.1    87      7   19
81    63.0    220.0  11.5    85      7   20
82    16.0      7.0   6.9    74      7   21
83     NaN    258.0   9.7    81      7   22
84     NaN    295.0  11.5    82      7   23
85    80.0    294.0   8.6    86      7   24
86   108.0    223.0   8.0    85      7   25
87    20.0     81.0   8.6    82      7   26
88    52.0     82.0  12.0    86      7   27
89    82.0    213.0   7.4    88      7   28
90    50.0    275.0   7.4    86      7   29
91    64.0    253.0   7.4    83      7   30
92    59.0    254.0   9.2    81      7   31
93    39.0     83.0   6.9    81      8    1
94     9.0     24.0  13.8    81      8    2
95    16.0     77.0   7.4    82      8    3
96    78.0      NaN   6.9    86      8    4
97    35.0      NaN   7.4    85      8    5
98    66.0      NaN   4.6    87      8    6
99   122.0    255.0   4.0    89      8    7
100   89.0    229.0  10.3    90      8    8
101  110.0    207.0   8.0    90      8    9
102    NaN    222.0   8.6    92      8   10
103    NaN    137.0  11.5    86      8   11
104   44.0    192.0  11.5    86      8   12
105   28.0    273.0  11.5    82      8   13
106   65.0    157.0   9.7    80      8   14
107    NaN     64.0  11.5    79      8   15
108   22.0     71.0  10.3    77      8   16
109   59.0     51.0   6.3    79      8   17
110   23.0    115.0   7.4    76      8   18
111   31.0    244.0  10.9    78      8   19
112   44.0    190.0  10.3    78      8   20
113   21.0    259.0  15.5    77      8   21
114    9.0     36.0  14.3    72      8   22
115    NaN    255.0  12.6    75      8   23
116   45.0    212.0   9.7    79      8   24
117  168.0    238.0   3.4    81      8   25
118   73.0    215.0   8.0    86      8   26
119    NaN    153.0   5.7    88      8   27
120   76.0    203.0   9.7    97      8   28
121  118.0    225.0   2.3    94      8   29
122   84.0    237.0   6.3    96      8   30
123   85.0    188.0   6.3    94      8   31
124   96.0    167.0   6.9    91      9    1
125   78.0    197.0   5.1    92      9    2
126   73.0    183.0   2.8    93      9    3
127   91.0    189.0   4.6    93      9    4
128   47.0     95.0   7.4    87      9    5
129   32.0     92.0  15.5    84      9    6
130   20.0    252.0  10.9    80      9    7
131   23.0    220.0  10.3    78      9    8
132   21.0    230.0  10.9    75      9    9
133   24.0    259.0   9.7    73      9   10
134   44.0    236.0  14.9    81      9   11
135   21.0    259.0  15.5    76      9   12
136   28.0    238.0   6.3    77      9   13
137    9.0     24.0  10.9    71      9   14
138   13.0    112.0  11.5    71      9   15
139   46.0    237.0   6.9    78      9   16
140   18.0    224.0  13.8    67      9   17
141   13.0     27.0  10.3    76      9   18
142   24.0    238.0  10.3    68      9   19
143   16.0    201.0   8.0    82      9   20
144   13.0    238.0  12.6    64      9   21
145   23.0     14.0   9.2    71      9   22
146   36.0    139.0  10.3    81      9   23
147    7.0     49.0  10.3    69      9   24
148   14.0     20.0  16.6    63      9   25
149   30.0    193.0   6.9    70      9   26
150    NaN    145.0  13.2    77      9   27
151   14.0    191.0  14.3    75      9   28
152   18.0    131.0   8.0    76      9   29
153   20.0    223.0  11.5    68      9   30

In [5]:
AQ.to_csv('airquality.csv', sep=',')

In [6]:
df = pd.read_csv(sep=',',filepath_or_buffer = 'airquality.csv', )

In [7]:
type(df)

pandas.core.frame.DataFrame

In [8]:
df.head()

   Unnamed: 0  Ozone  Solar.R  Wind  Temp  Month  Day
0           1   41.0    190.0   7.4    67      5    1
1           2   36.0    118.0   8.0    72      5    2
2           3   12.0    149.0  12.6    74      5    3
3           4   18.0    313.0  11.5    62      5    4
4           5    NaN      NaN  14.3    56      5    5

In [9]:
df.tail(n=10)

     Unnamed: 0  Ozone  Solar.R  Wind  Temp  Month  Day
143         144   13.0    238.0  12.6    64      9   21
144         145   23.0     14.0   9.2    71      9   22
145         146   36.0    139.0  10.3    81      9   23
146         147    7.0     49.0  10.3    69      9   24
147         148   14.0     20.0  16.6    63      9   25
148         149   30.0    193.0   6.9    70      9   26
149         150    NaN    145.0  13.2    77      9   27
150         151   14.0    191.0  14.3    75      9   28
151         152   18.0    131.0   8.0    76      9   29
152         153   20.0    223.0  11.5    68      9   30

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 153 entries, 0 to 152
Data columns (total 7 columns):
Unnamed: 0    153 non-null int64
Ozone         116 non-null float64
Solar.R       146 non-null float64
Wind          153 non-null float64
Temp          153 non-null int64
Month         153 non-null int64
Day           153 non-null int64
dtypes: float64(3), int64(4)
memory usage: 8.4 KB

In [11]:
df.describe()

,Unnamed: 0,Ozone,Solar.R,Wind,Temp,Month,Day
count,153.000000,116.000000,146.000000,153.000000,153.000000,153.000000,153.000000
mean,77.000000,42.129310,185.931507,9.957516,77.882353,6.993464,15.803922
std,44.311398,32.987885,90.058422,3.523001,9.465270,1.416522,8.864520
min,1.000000,1.000000,7.000000,1.700000,56.000000,5.000000,1.000000
25%,39.000000,18.000000,115.750000,7.400000,72.000000,6.000000,8.000000
50%,77.000000,31.500000,205.000000,9.700000,79.000000,7.000000,16.000000
75%,115.000000,63.250000,258.750000,11.500000,85.000000,8.000000,23.000000
max,153.000000,168.000000,334.000000,20.700000,97.000000,9.000000,31.000000

In [12]:
df['Ozone'].value_counts(dropna=False)

NaN       37
 23.0      6
 21.0      4
 13.0      4
 20.0      4
 18.0      4
 14.0      4
 16.0      4
 7.0       3
 11.0      3
 44.0      3
 9.0       3
 28.0      3
 32.0      3
 30.0      2
 85.0      2
 24.0      2
 39.0      2
 35.0      2
 37.0      2
 45.0      2
 97.0      2
 59.0      2
 78.0      2
 73.0      2
 12.0      2
 36.0      2
 64.0      2
 1.0       1
 4.0       1
 135.0     1
 115.0     1
 29.0      1
 6.0       1
 71.0      1
 34.0      1
 8.0       1
 19.0      1
 46.0      1
 49.0      1
 122.0     1
 47.0      1
 91.0      1
 96.0      1
 84.0      1
 118.0     1
 76.0      1
 168.0     1
 31.0      1
 22.0      1
 65.0      1
 110.0     1
 89.0      1
 66.0      1
 40.0      1
 50.0      1
 82.0      1
 52.0      1
 108.0     1
 80.0      1
 63.0      1
 79.0      1
 61.0      1
 48.0      1
 27.0      1
 10.0      1
 77.0      1
 41.0      1
Name: Ozone, dtype: int64

In [13]:
for a,b in AQ.iterrows():
    print(a,b)

1 Ozone       41.0
Solar.R    190.0
Wind         7.4
Temp        67.0
Month        5.0
Day          1.0
Name: 1, dtype: float64
2 Ozone       36.0
Solar.R    118.0
Wind         8.0
Temp        72.0
Month        5.0
Day          2.0
Name: 2, dtype: float64
3 Ozone       12.0
Solar.R    149.0
Wind        12.6
Temp        74.0
Month        5.0
Day          3.0
Name: 3, dtype: float64
4 Ozone       18.0
Solar.R    313.0
Wind        11.5
Temp        62.0
Month        5.0
Day          4.0
Name: 4, dtype: float64
5 Ozone       NaN
Solar.R     NaN
Wind       14.3
Temp       56.0
Month       5.0
Day         5.0
Name: 5, dtype: float64
6 Ozone      28.0
Solar.R     NaN
Wind       14.9
Temp       66.0
Month       5.0
Day         6.0
Name: 6, dtype: float64
7 Ozone       23.0
Solar.R    299.0
Wind         8.6
Temp        65.0
Month        5.0
Day          7.0
Name: 7, dtype: float64
8 Ozone      19.0
Solar.R    99.0
Wind       13.8
Temp       59.0
Month       5.0
Day         8.0
Name: 8, dtype: float64
9 Ozone       8.0
Solar.R    19.0
Wind       20.1
Temp       61.0
Month       5.0
Day         9.0
Name: 9, dtype: float64
10 Ozone        NaN
Solar.R    194.0
Wind         8.6
Temp        69.0
Month        5.0
Day         10.0
Name: 10, dtype: float64
11 Ozone       7.0
Solar.R     NaN
Wind        6.9
Temp       74.0
Month       5.0
Day        11.0
Name: 11, dtype: float64
12 Ozone       16.0
Solar.R    256.0
Wind         9.7
Temp        69.0
Month        5.0
Day         12.0
Name: 12, dtype: float64
13 Ozone       11.0
Solar.R    290.0
Wind         9.2
Temp        66.0
Month        5.0
Day         13.0
Name: 13, dtype: float64
14 Ozone       14.0
Solar.R    274.0
Wind        10.9
Temp        68.0
Month        5.0
Day         14.0
Name: 14, dtype: float64
15 Ozone      18.0
Solar.R    65.0
Wind       13.2
Temp       58.0
Month       5.0
Day        15.0
Name: 15, dtype: float64
16 Ozone       14.0
Solar.R    334.0
Wind        11.5
Temp        64.0
Month        5.0
Day         16.0
Name: 16, dtype: float64
17 Ozone       34.0
Solar.R    307.0
Wind        12.0
Temp        66.0
Month        5.0
Day         17.0
Name: 17, dtype: float64
18 Ozone       6.0
Solar.R    78.0
Wind       18.4
Temp       57.0
Month       5.0
Day        18.0
Name: 18, dtype: float64
19 Ozone       30.0
Solar.R    322.0
Wind        11.5
Temp        68.0
Month        5.0
Day         19.0
Name: 19, dtype: float64
20 Ozone      11.0
Solar.R    44.0
Wind        9.7
Temp       62.0
Month       5.0
Day        20.0
Name: 20, dtype: float64
21 Ozone       1.0
Solar.R     8.0
Wind        9.7
Temp       59.0
Month       5.0
Day        21.0
Name: 21, dtype: float64
22 Ozone       11.0
Solar.R    320.0
Wind        16.6
Temp        73.0
Month        5.0
Day         22.0
Name: 22, dtype: float64
23 Ozone       4.0
Solar.R    25.0
Wind        9.7
Temp       61.0
Month       5.0
Day        23.0
Name: 23, dtype: float64
24 Ozone      32.0
Solar.R    92.0
Wind       12.0
Temp       61.0
Month       5.0
Day        24.0
Name: 24, dtype: float64
25 Ozone       NaN
Solar.R    66.0
Wind       16.6
Temp       57.0
Month       5.0
Day        25.0
Name: 25, dtype: float64
26 Ozone        NaN
Solar.R    266.0
Wind        14.9
Temp        58.0
Month        5.0
Day         26.0
Name: 26, dtype: float64
27 Ozone       NaN
Solar.R     NaN
Wind        8.0
Temp       57.0
Month       5.0
Day        27.0
Name: 27, dtype: float64
28 Ozone      23.0
Solar.R    13.0
Wind       12.0
Temp       67.0
Month       5.0
Day        28.0
Name: 28, dtype: float64
29 Ozone       45.0
Solar.R    252.0
Wind        14.9
Temp        81.0
Month        5.0
Day         29.0
Name: 29, dtype: float64
30 Ozone      115.0
Solar.R    223.0
Wind         5.7
Temp        79.0
Month        5.0
Day         30.0
Name: 30, dtype: float64
31 Ozone       37.0
Solar.R    279.0
Wind         7.4
Temp        76.0
Month        5.0
Day         31.0
Name: 31, dtype: float64
32 Ozone        NaN
Solar.R    286.0
Wind         8.6
Temp        78.0
Month        6.0
Day          1.0
Name: 32, dtype: float64
33 Ozone        NaN
Solar.R    287.0
Wind         9.7
Temp        74.0
Month        6.0
Day          2.0
Name: 33, dtype: float64
34 Ozone        NaN
Solar.R    242.0
Wind        16.1
Temp        67.0
Month        6.0
Day          3.0
Name: 34, dtype: float64
35 Ozone        NaN
Solar.R    186.0
Wind         9.2
Temp        84.0
Month        6.0
Day          4.0
Name: 35, dtype: float64
36 Ozone        NaN
Solar.R    220.0
Wind         8.6
Temp        85.0
Month        6.0
Day          5.0
Name: 36, dtype: float64
37 Ozone        NaN
Solar.R    264.0
Wind        14.3
Temp        79.0
Month        6.0
Day          6.0
Name: 37, dtype: float64
38 Ozone       29.0
Solar.R    127.0
Wind         9.7
Temp        82.0
Month        6.0
Day          7.0
Name: 38, dtype: float64
39 Ozone        NaN
Solar.R    273.0
Wind         6.9
Temp        87.0
Month        6.0
Day          8.0
Name: 39, dtype: float64
40 Ozone       71.0
Solar.R    291.0
Wind        13.8
Temp        90.0
Month        6.0
Day          9.0
Name: 40, dtype: float64
41 Ozone       39.0
Solar.R    323.0
Wind        11.5
Temp        87.0
Month        6.0
Day         10.0
Name: 41, dtype: float64
42 Ozone        NaN
Solar.R    259.0
Wind        10.9
Temp        93.0
Month        6.0
Day         11.0
Name: 42, dtype: float64
43 Ozone        NaN
Solar.R    250.0
Wind         9.2
Temp        92.0
Month        6.0
Day         12.0
Name: 43, dtype: float64
44 Ozone       23.0
Solar.R    148.0
Wind         8.0
Temp        82.0
Month        6.0
Day         13.0
Name: 44, dtype: float64
45 Ozone        NaN
Solar.R    332.0
Wind        13.8
Temp        80.0
Month        6.0
Day         14.0
Name: 45, dtype: float64
46 Ozone        NaN
Solar.R    322.0
Wind        11.5
Temp        79.0
Month        6.0
Day         15.0
Name: 46, dtype: float64
47 Ozone       21.0
Solar.R    191.0
Wind        14.9
Temp        77.0
Month        6.0
Day         16.0
Name: 47, dtype: float64
48 Ozone       37.0
Solar.R    284.0
Wind        20.7
Temp        72.0
Month        6.0
Day         17.0
Name: 48, dtype: float64
49 Ozone      20.0
Solar.R    37.0
Wind        9.2
Temp       65.0
Month       6.0
Day        18.0
Name: 49, dtype: float64
50 Ozone       12.0
Solar.R    120.0
Wind        11.5
Temp        73.0
Month        6.0
Day         19.0
Name: 50, dtype: float64
51 Ozone       13.0
Solar.R    137.0
Wind        10.3
Temp        76.0
Month        6.0
Day         20.0
Name: 51, dtype: float64
52 Ozone        NaN
Solar.R    150.0
Wind         6.3
Temp        77.0
Month        6.0
Day         21.0
Name: 52, dtype: float64
53 Ozone       NaN
Solar.R    59.0
Wind        1.7
Temp       76.0
Month       6.0
Day        22.0
Name: 53, dtype: float64
54 Ozone       NaN
Solar.R    91.0
Wind        4.6
Temp       76.0
Month       6.0
Day        23.0
Name: 54, dtype: float64
55 Ozone        NaN
Solar.R    250.0
Wind         6.3
Temp        76.0
Month        6.0
Day         24.0
Name: 55, dtype: float64
56 Ozone        NaN
Solar.R    135.0
Wind         8.0
Temp        75.0
Month        6.0
Day         25.0
Name: 56, dtype: float64
57 Ozone        NaN
Solar.R    127.0
Wind         8.0
Temp        78.0
Month        6.0
Day         26.0
Name: 57, dtype: float64
58 Ozone       NaN
Solar.R    47.0
Wind       10.3
Temp       73.0
Month       6.0
Day        27.0
Name: 58, dtype: float64
59 Ozone       NaN
Solar.R    98.0
Wind       11.5
Temp       80.0
Month       6.0
Day        28.0
Name: 59, dtype: float64
60 Ozone       NaN
Solar.R    31.0
Wind       14.9
Temp       77.0
Month       6.0
Day        29.0
Name: 60, dtype: float64
61 Ozone        NaN
Solar.R    138.0
Wind         8.0
Temp        83.0
Month        6.0
Day         30.0
Name: 61, dtype: float64
62 Ozone      135.0
Solar.R    269.0
Wind         4.1
Temp        84.0
Month        7.0
Day          1.0
Name: 62, dtype: float64
63 Ozone       49.0
Solar.R    248.0
Wind         9.2
Temp        85.0
Month        7.0
Day          2.0
Name: 63, dtype: float64
64 Ozone       32.0
Solar.R    236.0
Wind         9.2
Temp        81.0
Month        7.0
Day          3.0
Name: 64, dtype: float64
65 Ozone        NaN
Solar.R    101.0
Wind        10.9
Temp        84.0
Month        7.0
Day          4.0
Name: 65, dtype: float64
66 Ozone       64.0
Solar.R    175.0
Wind         4.6
Temp        83.0
Month        7.0
Day          5.0
Name: 66, dtype: float64
67 Ozone       40.0
Solar.R    314.0
Wind        10.9
Temp        83.0
Month        7.0
Day          6.0
Name: 67, dtype: float64
68 Ozone       77.0
Solar.R    276.0
Wind         5.1
Temp        88.0
Month        7.0
Day          7.0
Name: 68, dtype: float64
69 Ozone       97.0
Solar.R    267.0
Wind         6.3
Temp        92.0
Month        7.0
Day          8.0
Name: 69, dtype: float64
70 Ozone       97.0
Solar.R    272.0
Wind         5.7
Temp        92.0
Month        7.0
Day          9.0
Name: 70, dtype: float64
71 Ozone       85.0
Solar.R    175.0
Wind         7.4
Temp        89.0
Month        7.0
Day         10.0
Name: 71, dtype: float64
72 Ozone        NaN
Solar.R    139.0
Wind         8.6
Temp        82.0
Month        7.0
Day         11.0
Name: 72, dtype: float64
73 Ozone       10.0
Solar.R    264.0
Wind        14.3
Temp        73.0
Month        7.0
Day         12.0
Name: 73, dtype: float64
74 Ozone       27.0
Solar.R    175.0
Wind        14.9
Temp        81.0
Month        7.0
Day         13.0
Name: 74, dtype: float64
75 Ozone        NaN
Solar.R    291.0
Wind        14.9
Temp        91.0
Month        7.0
Day         14.0
Name: 75, dtype: float64
76 Ozone       7.0
Solar.R    48.0
Wind       14.3
Temp       80.0
Month       7.0
Day        15.0
Name: 76, dtype: float64
77 Ozone       48.0
Solar.R    260.0
Wind         6.9
Temp        81.0
Month        7.0
Day         16.0
Name: 77, dtype: float64
78 Ozone       35.0
Solar.R    274.0
Wind        10.3
Temp        82.0
Month        7.0
Day         17.0
Name: 78, dtype: float64
79 Ozone       61.0
Solar.R    285.0
Wind         6.3
Temp        84.0
Month        7.0
Day         18.0
Name: 79, dtype: float64
80 Ozone       79.0
Solar.R    187.0
Wind         5.1
Temp        87.0
Month        7.0
Day         19.0
Name: 80, dtype: float64
81 Ozone       63.0
Solar.R    220.0
Wind        11.5
Temp        85.0
Month        7.0
Day         20.0
Name: 81, dtype: float64
82 Ozone      16.0
Solar.R     7.0
Wind        6.9
Temp       74.0
Month       7.0
Day        21.0
Name: 82, dtype: float64
83 Ozone        NaN
Solar.R    258.0
Wind         9.7
Temp        81.0
Month        7.0
Day         22.0
Name: 83, dtype: float64
84 Ozone        NaN
Solar.R    295.0
Wind        11.5
Temp        82.0
Month        7.0
Day         23.0
Name: 84, dtype: float64
85 Ozone       80.0
Solar.R    294.0
Wind         8.6
Temp        86.0
Month        7.0
Day         24.0
Name: 85, dtype: float64
86 Ozone      108.0
Solar.R    223.0
Wind         8.0
Temp        85.0
Month        7.0
Day         25.0
Name: 86, dtype: float64
87 Ozone      20.0
Solar.R    81.0
Wind        8.6
Temp       82.0
Month       7.0
Day        26.0
Name: 87, dtype: float64
88 Ozone      52.0
Solar.R    82.0
Wind       12.0
Temp       86.0
Month       7.0
Day        27.0
Name: 88, dtype: float64
89 Ozone       82.0
Solar.R    213.0
Wind         7.4
Temp        88.0
Month        7.0
Day         28.0
Name: 89, dtype: float64
90 Ozone       50.0
Solar.R    275.0
Wind         7.4
Temp        86.0
Month        7.0
Day         29.0
Name: 90, dtype: float64
91 Ozone       64.0
Solar.R    253.0
Wind         7.4
Temp        83.0
Month        7.0
Day         30.0
Name: 91, dtype: float64
92 Ozone       59.0
Solar.R    254.0
Wind         9.2
Temp        81.0
Month        7.0
Day         31.0
Name: 92, dtype: float64
93 Ozone      39.0
Solar.R    83.0
Wind        6.9
Temp       81.0
Month       8.0
Day         1.0
Name: 93, dtype: float64
94 Ozone       9.0
Solar.R    24.0
Wind       13.8
Temp       81.0
Month       8.0
Day         2.0
Name: 94, dtype: float64
95 Ozone      16.0
Solar.R    77.0
Wind        7.4
Temp       82.0
Month       8.0
Day         3.0
Name: 95, dtype: float64
96 Ozone      78.0
Solar.R     NaN
Wind        6.9
Temp       86.0
Month       8.0
Day         4.0
Name: 96, dtype: float64
97 Ozone      35.0
Solar.R     NaN
Wind        7.4
Temp       85.0
Month       8.0
Day         5.0
Name: 97, dtype: float64
98 Ozone      66.0
Solar.R     NaN
Wind        4.6
Temp       87.0
Month       8.0
Day         6.0
Name: 98, dtype: float64
99 Ozone      122.0
Solar.R    255.0
Wind         4.0
Temp        89.0
Month        8.0
Day          7.0
Name: 99, dtype: float64
100 Ozone       89.0
Solar.R    229.0
Wind        10.3
Temp        90.0
Month        8.0
Day          8.0
Name: 100, dtype: float64
101 Ozone      110.0
Solar.R    207.0
Wind         8.0
Temp        90.0
Month        8.0
Day          9.0
Name: 101, dtype: float64
102 Ozone        NaN
Solar.R    222.0
Wind         8.6
Temp        92.0
Month        8.0
Day         10.0
Name: 102, dtype: float64
103 Ozone        NaN
Solar.R    137.0
Wind        11.5
Temp        86.0
Month        8.0
Day         11.0
Name: 103, dtype: float64
104 Ozone       44.0
Solar.R    192.0
Wind        11.5
Temp        86.0
Month        8.0
Day         12.0
Name: 104, dtype: float64
105 Ozone       28.0
Solar.R    273.0
Wind        11.5
Temp        82.0
Month        8.0
Day         13.0
Name: 105, dtype: float64
106 Ozone       65.0
Solar.R    157.0
Wind         9.7
Temp        80.0
Month        8.0
Day         14.0
Name: 106, dtype: float64
107 Ozone       NaN
Solar.R    64.0
Wind       11.5
Temp       79.0
Month       8.0
Day        15.0
Name: 107, dtype: float64
108 Ozone      22.0
Solar.R    71.0
Wind       10.3
Temp       77.0
Month       8.0
Day        16.0
Name: 108, dtype: float64
109 Ozone      59.0
Solar.R    51.0
Wind        6.3
Temp       79.0
Month       8.0
Day        17.0
Name: 109, dtype: float64
110 Ozone       23.0
Solar.R    115.0
Wind         7.4
Temp        76.0
Month        8.0
Day         18.0
Name: 110, dtype: float64
111 Ozone       31.0
Solar.R    244.0
Wind        10.9
Temp        78.0
Month        8.0
Day         19.0
Name: 111, dtype: float64
112 Ozone       44.0
Solar.R    190.0
Wind        10.3
Temp        78.0
Month        8.0
Day         20.0
Name: 112, dtype: float64
113 Ozone       21.0
Solar.R    259.0
Wind        15.5
Temp        77.0
Month        8.0
Day         21.0
Name: 113, dtype: float64
114 Ozone       9.0
Solar.R    36.0
Wind       14.3
Temp       72.0
Month       8.0
Day        22.0
Name: 114, dtype: float64
115 Ozone        NaN
Solar.R    255.0
Wind        12.6
Temp        75.0
Month        8.0
Day         23.0
Name: 115, dtype: float64
116 Ozone       45.0
Solar.R    212.0
Wind         9.7
Temp        79.0
Month        8.0
Day         24.0
Name: 116, dtype: float64
117 Ozone      168.0
Solar.R    238.0
Wind         3.4
Temp        81.0
Month        8.0
Day         25.0
Name: 117, dtype: float64
118 Ozone       73.0
Solar.R    215.0
Wind         8.0
Temp        86.0
Month        8.0
Day         26.0
Name: 118, dtype: float64
119 Ozone        NaN
Solar.R    153.0
Wind         5.7
Temp        88.0
Month        8.0
Day         27.0
Name: 119, dtype: float64
120 Ozone       76.0
Solar.R    203.0
Wind         9.7
Temp        97.0
Month        8.0
Day         28.0
Name: 120, dtype: float64
121 Ozone      118.0
Solar.R    225.0
Wind         2.3
Temp        94.0
Month        8.0
Day         29.0
Name: 121, dtype: float64
122 Ozone       84.0
Solar.R    237.0
Wind         6.3
Temp        96.0
Month        8.0
Day         30.0
Name: 122, dtype: float64
123 Ozone       85.0
Solar.R    188.0
Wind         6.3
Temp        94.0
Month        8.0
Day         31.0
Name: 123, dtype: float64
124 Ozone       96.0
Solar.R    167.0
Wind         6.9
Temp        91.0
Month        9.0
Day          1.0
Name: 124, dtype: float64
125 Ozone       78.0
Solar.R    197.0
Wind         5.1
Temp        92.0
Month        9.0
Day          2.0
Name: 125, dtype: float64
126 Ozone       73.0
Solar.R    183.0
Wind         2.8
Temp        93.0
Month        9.0
Day          3.0
Name: 126, dtype: float64
127 Ozone       91.0
Solar.R    189.0
Wind         4.6
Temp        93.0
Month        9.0
Day          4.0
Name: 127, dtype: float64
128 Ozone      47.0
Solar.R    95.0
Wind        7.4
Temp       87.0
Month       9.0
Day         5.0
Name: 128, dtype: float64
129 Ozone      32.0
Solar.R    92.0
Wind       15.5
Temp       84.0
Month       9.0
Day         6.0
Name: 129, dtype: float64
130 Ozone       20.0
Solar.R    252.0
Wind        10.9
Temp        80.0
Month        9.0
Day          7.0
Name: 130, dtype: float64
131 Ozone       23.0
Solar.R    220.0
Wind        10.3
Temp        78.0
Month        9.0
Day          8.0
Name: 131, dtype: float64
132 Ozone       21.0
Solar.R    230.0
Wind        10.9
Temp        75.0
Month        9.0
Day          9.0
Name: 132, dtype: float64
133 Ozone       24.0
Solar.R    259.0
Wind         9.7
Temp        73.0
Month        9.0
Day         10.0
Name: 133, dtype: float64
134 Ozone       44.0
Solar.R    236.0
Wind        14.9
Temp        81.0
Month        9.0
Day         11.0
Name: 134, dtype: float64
135 Ozone       21.0
Solar.R    259.0
Wind        15.5
Temp        76.0
Month        9.0
Day         12.0
Name: 135, dtype: float64
136 Ozone       28.0
Solar.R    238.0
Wind         6.3
Temp        77.0
Month        9.0
Day         13.0
Name: 136, dtype: float64
137 Ozone       9.0
Solar.R    24.0
Wind       10.9
Temp       71.0
Month       9.0
Day        14.0
Name: 137, dtype: float64
138 Ozone       13.0
Solar.R    112.0
Wind        11.5
Temp        71.0
Month        9.0
Day         15.0
Name: 138, dtype: float64
139 Ozone       46.0
Solar.R    237.0
Wind         6.9
Temp        78.0
Month        9.0
Day         16.0
Name: 139, dtype: float64
140 Ozone       18.0
Solar.R    224.0
Wind        13.8
Temp        67.0
Month        9.0
Day         17.0
Name: 140, dtype: float64
141 Ozone      13.0
Solar.R    27.0
Wind       10.3
Temp       76.0
Month       9.0
Day        18.0
Name: 141, dtype: float64
142 Ozone       24.0
Solar.R    238.0
Wind        10.3
Temp        68.0
Month        9.0
Day         19.0
Name: 142, dtype: float64
143 Ozone       16.0
Solar.R    201.0
Wind         8.0
Temp        82.0
Month        9.0
Day         20.0
Name: 143, dtype: float64
144 Ozone       13.0
Solar.R    238.0
Wind        12.6
Temp        64.0
Month        9.0
Day         21.0
Name: 144, dtype: float64
145 Ozone      23.0
Solar.R    14.0
Wind        9.2
Temp       71.0
Month       9.0
Day        22.0
Name: 145, dtype: float64
146 Ozone       36.0
Solar.R    139.0
Wind        10.3
Temp        81.0
Month        9.0
Day         23.0
Name: 146, dtype: float64
147 Ozone       7.0
Solar.R    49.0
Wind       10.3
Temp       69.0
Month       9.0
Day        24.0
Name: 147, dtype: float64
148 Ozone      14.0
Solar.R    20.0
Wind       16.6
Temp       63.0
Month       9.0
Day        25.0
Name: 148, dtype: float64
149 Ozone       30.0
Solar.R    193.0
Wind         6.9
Temp        70.0
Month        9.0
Day         26.0
Name: 149, dtype: float64
150 Ozone        NaN
Solar.R    145.0
Wind        13.2
Temp        77.0
Month        9.0
Day         27.0
Name: 150, dtype: float64
151 Ozone       14.0
Solar.R    191.0
Wind        14.3
Temp        75.0
Month        9.0
Day         28.0
Name: 151, dtype: float64
152 Ozone       18.0
Solar.R    131.0
Wind         8.0
Temp        76.0
Month        9.0
Day         29.0
Name: 152, dtype: float64
153 Ozone       20.0
Solar.R    223.0
Wind        11.5
Temp        68.0
Month        9.0
Day         30.0
Name: 153, dtype: float64

In [14]:
df[['Ozone','Temp']]

     Ozone  Temp
0     41.0    67
1     36.0    72
2     12.0    74
3     18.0    62
4      NaN    56
5     28.0    66
6     23.0    65
7     19.0    59
8      8.0    61
9      NaN    69
10     7.0    74
11    16.0    69
12    11.0    66
13    14.0    68
14    18.0    58
15    14.0    64
16    34.0    66
17     6.0    57
18    30.0    68
19    11.0    62
20     1.0    59
21    11.0    73
22     4.0    61
23    32.0    61
24     NaN    57
25     NaN    58
26     NaN    57
27    23.0    67
28    45.0    81
29   115.0    79
30    37.0    76
31     NaN    78
32     NaN    74
33     NaN    67
34     NaN    84
35     NaN    85
36     NaN    79
37    29.0    82
38     NaN    87
39    71.0    90
40    39.0    87
41     NaN    93
42     NaN    92
43    23.0    82
44     NaN    80
45     NaN    79
46    21.0    77
47    37.0    72
48    20.0    65
49    12.0    73
50    13.0    76
51     NaN    77
52     NaN    76
53     NaN    76
54     NaN    76
55     NaN    75
56     NaN    78
57     NaN    73
58     NaN    80
59     NaN    77
60     NaN    83
61   135.0    84
62    49.0    85
63    32.0    81
64     NaN    84
65    64.0    83
66    40.0    83
67    77.0    88
68    97.0    92
69    97.0    92
70    85.0    89
71     NaN    82
72    10.0    73
73    27.0    81
74     NaN    91
75     7.0    80
76    48.0    81
77    35.0    82
78    61.0    84
79    79.0    87
80    63.0    85
81    16.0    74
82     NaN    81
83     NaN    82
84    80.0    86
85   108.0    85
86    20.0    82
87    52.0    86
88    82.0    88
89    50.0    86
90    64.0    83
91    59.0    81
92    39.0    81
93     9.0    81
94    16.0    82
95    78.0    86
96    35.0    85
97    66.0    87
98   122.0    89
99    89.0    90
100  110.0    90
101    NaN    92
102    NaN    86
103   44.0    86
104   28.0    82
105   65.0    80
106    NaN    79
107   22.0    77
108   59.0    79
109   23.0    76
110   31.0    78
111   44.0    78
112   21.0    77
113    9.0    72
114    NaN    75
115   45.0    79
116  168.0    81
117   73.0    86
118    NaN    88
119   76.0    97
120  118.0    94
121   84.0    96
122   85.0    94
123   96.0    91
124   78.0    92
125   73.0    93
126   91.0    93
127   47.0    87
128   32.0    84
129   20.0    80
130   23.0    78
131   21.0    75
132   24.0    73
133   44.0    81
134   21.0    76
135   28.0    77
136    9.0    71
137   13.0    71
138   46.0    78
139   18.0    67
140   13.0    76
141   24.0    68
142   16.0    82
143   13.0    64
144   23.0    71
145   36.0    81
146    7.0    69
147   14.0    63
148   30.0    70
149    NaN    77
150   14.0    75
151   18.0    76
152   20.0    68

In [15]:
df[1:3]

   Unnamed: 0  Ozone  Solar.R  Wind  Temp  Month  Day
1           2   36.0    118.0   8.0    72      5    2
2           3   12.0    149.0  12.6    74      5    3

In [16]:
df.loc[1:50,['Ozone','Temp']]

    Ozone  Temp
1    36.0    72
2    12.0    74
3    18.0    62
4     NaN    56
5    28.0    66
6    23.0    65
7    19.0    59
8     8.0    61
9     NaN    69
10    7.0    74
11   16.0    69
12   11.0    66
13   14.0    68
14   18.0    58
15   14.0    64
16   34.0    66
17    6.0    57
18   30.0    68
19   11.0    62
20    1.0    59
21   11.0    73
22    4.0    61
23   32.0    61
24    NaN    57
25    NaN    58
26    NaN    57
27   23.0    67
28   45.0    81
29  115.0    79
30   37.0    76
31    NaN    78
32    NaN    74
33    NaN    67
34    NaN    84
35    NaN    85
36    NaN    79
37   29.0    82
38    NaN    87
39   71.0    90
40   39.0    87
41    NaN    93
42    NaN    92
43   23.0    82
44    NaN    80
45    NaN    79
46   21.0    77
47   37.0    72
48   20.0    65
49   12.0    73
50   13.0    76

In [22]:
df.iloc[1:5,0:3]

   Unnamed: 0  Ozone  Solar.R
1           2   36.0    118.0
2           3   12.0    149.0
3           4   18.0    313.0
4           5    NaN      NaN

In [23]:
df.iloc[[1,50],0:3]

    Unnamed: 0  Ozone  Solar.R
1            2   36.0    118.0
50          51   13.0    137.0

In [25]:
df.iloc[1:5,[1,2,3]]

   Ozone  Solar.R  Wind
1   36.0    118.0   8.0
2   12.0    149.0  12.6
3   18.0    313.0  11.5
4    NaN      NaN  14.3

In [51]:
high_temp = df['Temp']>78
df[high_temp]

     Unnamed: 0  Ozone  Solar.R  Wind  Temp  Month  Day
28           29   45.0    252.0  14.9    81      5   29
29           30  115.0    223.0   5.7    79      5   30
34           35    NaN    186.0   9.2    84      6    4
35           36    NaN    220.0   8.6    85      6    5
36           37    NaN    264.0  14.3    79      6    6
37           38   29.0    127.0   9.7    82      6    7
38           39    NaN    273.0   6.9    87      6    8
39           40   71.0    291.0  13.8    90      6    9
40           41   39.0    323.0  11.5    87      6   10
41           42    NaN    259.0  10.9    93      6   11
42           43    NaN    250.0   9.2    92      6   12
43           44   23.0    148.0   8.0    82      6   13
44           45    NaN    332.0  13.8    80      6   14
45           46    NaN    322.0  11.5    79      6   15
58           59    NaN     98.0  11.5    80      6   28
60           61    NaN    138.0   8.0    83      6   30
61           62  135.0    269.0   4.1    84      7    1
62           63   49.0    248.0   9.2    85      7    2
63           64   32.0    236.0   9.2    81      7    3
64           65    NaN    101.0  10.9    84      7    4
65           66   64.0    175.0   4.6    83      7    5
66           67   40.0    314.0  10.9    83      7    6
67           68   77.0    276.0   5.1    88      7    7
68           69   97.0    267.0   6.3    92      7    8
69           70   97.0    272.0   5.7    92      7    9
70           71   85.0    175.0   7.4    89      7   10
71           72    NaN    139.0   8.6    82      7   11
73           74   27.0    175.0  14.9    81      7   13
74           75    NaN    291.0  14.9    91      7   14
75           76    7.0     48.0  14.3    80      7   15
76           77   48.0    260.0   6.9    81      7   16
77           78   35.0    274.0  10.3    82      7   17
78           79   61.0    285.0   6.3    84      7   18
79           80   79.0    187.0   5.1    87      7   19
80           81   63.0    220.0  11.5    85      7   20
82           83    NaN    258.0   9.7    81      7   22
83           84    NaN    295.0  11.5    82      7   23
84           85   80.0    294.0   8.6    86      7   24
85           86  108.0    223.0   8.0    85      7   25
86           87   20.0     81.0   8.6    82      7   26
87           88   52.0     82.0  12.0    86      7   27
88           89   82.0    213.0   7.4    88      7   28
89           90   50.0    275.0   7.4    86      7   29
90           91   64.0    253.0   7.4    83      7   30
91           92   59.0    254.0   9.2    81      7   31
92           93   39.0     83.0   6.9    81      8    1
93           94    9.0     24.0  13.8    81      8    2
94           95   16.0     77.0   7.4    82      8    3
95           96   78.0      NaN   6.9    86      8    4
96           97   35.0      NaN   7.4    85      8    5
97           98   66.0      NaN   4.6    87      8    6
98           99  122.0    255.0   4.0    89      8    7
99          100   89.0    229.0  10.3    90      8    8
100         101  110.0    207.0   8.0    90      8    9
101         102    NaN    222.0   8.6    92      8   10
102         103    NaN    137.0  11.5    86      8   11
103         104   44.0    192.0  11.5    86      8   12
104         105   28.0    273.0  11.5    82      8   13
105         106   65.0    157.0   9.7    80      8   14
106         107    NaN     64.0  11.5    79      8   15
108         109   59.0     51.0   6.3    79      8   17
115         116   45.0    212.0   9.7    79      8   24
116         117  168.0    238.0   3.4    81      8   25
117         118   73.0    215.0   8.0    86      8   26
118         119    NaN    153.0   5.7    88      8   27
119         120   76.0    203.0   9.7    97      8   28
120         121  118.0    225.0   2.3    94      8   29
121         122   84.0    237.0   6.3    96      8   30
122         123   85.0    188.0   6.3    94      8   31
123         124   96.0    167.0   6.9    91      9    1
124         125   78.0    197.0   5.1    92      9    2
125         126   73.0    183.0   2.8    93      9    3
126         127   91.0    189.0   4.6    93      9    4
127         128   47.0     95.0   7.4    87      9    5
128         129   32.0     92.0  15.5    84      9    6
129         130   20.0    252.0  10.9    80      9    7
133         134   44.0    236.0  14.9    81      9   11
142         143   16.0    201.0   8.0    82      9   20
145         146   36.0    139.0  10.3    81      9   23

In [52]:
df[df['Temp']>78].shape

(79, 7)

In [53]:
df[(df['Temp']>78) & (df['Ozone'] > 42)]

     Unnamed: 0  Ozone  Solar.R  Wind  Temp  Month  Day
28           29   45.0    252.0  14.9    81      5   29
29           30  115.0    223.0   5.7    79      5   30
39           40   71.0    291.0  13.8    90      6    9
61           62  135.0    269.0   4.1    84      7    1
62           63   49.0    248.0   9.2    85      7    2
65           66   64.0    175.0   4.6    83      7    5
67           68   77.0    276.0   5.1    88      7    7
68           69   97.0    267.0   6.3    92      7    8
69           70   97.0    272.0   5.7    92      7    9
70           71   85.0    175.0   7.4    89      7   10
76           77   48.0    260.0   6.9    81      7   16
78           79   61.0    285.0   6.3    84      7   18
79           80   79.0    187.0   5.1    87      7   19
80           81   63.0    220.0  11.5    85      7   20
84           85   80.0    294.0   8.6    86      7   24
85           86  108.0    223.0   8.0    85      7   25
87           88   52.0     82.0  12.0    86      7   27
88           89   82.0    213.0   7.4    88      7   28
89           90   50.0    275.0   7.4    86      7   29
90           91   64.0    253.0   7.4    83      7   30
91           92   59.0    254.0   9.2    81      7   31
95           96   78.0      NaN   6.9    86      8    4
97           98   66.0      NaN   4.6    87      8    6
98           99  122.0    255.0   4.0    89      8    7
99          100   89.0    229.0  10.3    90      8    8
100         101  110.0    207.0   8.0    90      8    9
103         104   44.0    192.0  11.5    86      8   12
105         106   65.0    157.0   9.7    80      8   14
108         109   59.0     51.0   6.3    79      8   17
115         116   45.0    212.0   9.7    79      8   24
116         117  168.0    238.0   3.4    81      8   25
117         118   73.0    215.0   8.0    86      8   26
119         120   76.0    203.0   9.7    97      8   28
120         121  118.0    225.0   2.3    94      8   29
121         122   84.0    237.0   6.3    96      8   30
122         123   85.0    188.0   6.3    94      8   31
123         124   96.0    167.0   6.9    91      9    1
124         125   78.0    197.0   5.1    92      9    2
125         126   73.0    183.0   2.8    93      9    3
126         127   91.0    189.0   4.6    93      9    4
127         128   47.0     95.0   7.4    87      9    5
133         134   44.0    236.0  14.9    81      9   11

In [56]:
[False,True] and [True,False]

[True, False]

In [27]:
import numpy as np
np.logical_and([False,True], [True, False])

array([False, False])

In [ ]:
pd.Series([False, True]) & pd.Series([True, False])